### PR TITLE
fixed the issue #71

### PR DESCRIPTION
**Pull request by Marco4763**

### CODE REVIEW

**Comment by robert-virkus** [comment]
Hey, thank you very much for your contribution, much appreciated!

**Comment by robert-virkus** [comment]
@Marco4763 
Thanks again for your contribution, please confirm that you agree with the contributor's license agreement as stated on https://github.com/Enough-Software/enough_mail_app/blob/main/CLA.md.

**Comment by robert-virkus** [comment]
recheck

**Comment by Marco4763** [comment]
I have read the CLA Document and I hereby sign and agree with the CLA.

**Comment by Marco4763** [comment]
recheck

**Comment by robert-virkus** [comment]
Thanks for confirming, there still seems to be an internal CLA bot problem, I will check this later.

**Pull request merged**
